# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 07:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'friends'), (2, 'followers')], db_index=True)),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('next_cursor', models.BigIntegerField(db_index=True)),
                ('previous_cursor', models.BigIntegerField(db_index=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
