# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'followers'},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'friends'},
        ),
    ]
