# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160901_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
