# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160921_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
