# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161014_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='follower_ids',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='friend_ids',
        ),
    ]
