# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160904_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='members',
            new_name='member_ids',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='subscribers',
            new_name='subscriber_ids',
        ),
    ]
