# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160920_0736'),
    ]

    operations = [
    ]
