# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160920_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='member_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='list',
            name='subscriber_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
