# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20161014_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
