# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20161017_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
