# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 04:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('permission', models.CharField(choices=[('r', 'read'), ('w', 'read & write'), ('m', 'read, write & messages')], default='r', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rate_limit_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.Application')),
            ],
        ),
    ]
